### ISSUE TITLE
How to add google analytics Script code

### ISSUE THREAD

**Issue by ytam** [TolgaTatli/Moon#109]
How I can embedded google analytics script code to see who visit my website.

**Comment by MrBowen** [comment]
Just add your Google Analytics ID in the file: _config.yml.
Wish that is helpful for you.

**Comment by ytam** [comment]
I add it but does not work

**Comment by ytam** [comment]
The page build failed with the following error:

You have an error on line 2 of your `_config.yml` file. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by MrBowen** [comment]
The mine is not my user ID, is a ID started with UA-9******.

**Comment by ytam** [comment]
I add that code but still does not work
