### ISSUE TITLE
How do you create projects?

### ISSUE THREAD

**Issue by jakefb** [TolgaTatli/Moon#119]
Hi I have a question, how do you create a project?

Thanks in advance!

**Comment by dale6998** [comment]
Duplicate of [#79](https://github.com/TaylanTatli/Moon/issues?utf8=%E2%9C%93&q=project).

You have to add `project: true` to the post header.  Post your posts in the usual place...no special folders named "project" or anything like that.

**Comment by wanlinjuan** [comment]
> Duplicate of [#79](https://github.com/TaylanTatli/Moon/issues?utf8=%E2%9C%93&q=project).
> 
> You have to add `project: true` to the post header. Post your posts in the usual place...no special folders named "project" or anything like that.

Thank you so much for your help!
