### ISSUE TITLE
Adding not listed social link

### ISSUE THREAD

**Issue by e-ivkov** [TolgaTatli/Moon#161]
Can you advice me how to add social link that is not listed in _config.yml file?

**Comment by Chewsterchew** [comment]
Yes! Very simple.
First, find the icon (if it exists) in the [FontAwesome Icon set](https://fontawesome.com/icons?d=gallery).
Moon is using font-awesome 4.7.0. If your icon's version is 4.7.0 or below, great! On the FA page, you'll see the fa-x code. Save that for later.

Open up your code, navigate to `_includes/social-links.html`
Add this line right before the bottom
```html
{% if site.SOCIALLINKHERE %}<a class="social-btn" href="BASEURL{{ site.SOCIALLINKHERE }}" target="_blank" rel="noopener noreferrer"><i class="fa fa-fw fa-SOCIALCODE"></i></a>{% endif %}
```

Replace SOCIALLINKHERE with a new item in your _config.yml
```yaml
bob: jerry
```

and replace SOCIALCODE with the code from before.


If the icon you're looking for is above v4.7.0 (e.g. Discord), you're gonna have to update FA manually, and I'm not to sure how to do this yet.

Hope this helps!
