### ISSUE TITLE
Change the logo in navigation

### ISSUE THREAD

**Issue by GaryZhangChn** [TolgaTatli/Moon#173]
Hello, I'm trying to change the picture located in the "about" inside the navigation button. However, it is synchronized and always shows the same icon as I configured in "logo". Is there a way to use a different image for that?

**Comment by jaharnum** [comment]
If you go into the `_includes/nav.html` file, you'll be able to find the code for the navigation "about" submenu. The class for the img is called "author-photo" and it's on line 9 if you haven't edited anything else from that file yet. 

The part that syncs it to the logo is "`{{ site.logo }}`". 

You can add a new subcategory like `about_img` or whatever else you like in the `_config.yml` file and then add the image path there (similar to the logo one) and then just change it to `{{ site.about_img }}` :)
