### ISSUE TITLE
Changing colour of the nav menu and the home hover button

### ISSUE THREAD

**Issue by herboratory** [TolgaTatli/Moon#187]
I would like to know how to change the background, menu icon and the font colour at the nav menu? Also the About and the Post button from red?

Many thanks!

**Comment by mzeml** [comment]
If you mean changing the color of the button when hovering (default behavior is it becomes red after you hover over it), do this:

In elements.scss, under %btnextend, got to &:hover. Under &:hover, change "color: $red" to whichever value you want that is located in variables.scss. For example, I changed it to "$info", but I assume you can add a new variable and use that if you'd want.
