### ISSUE TITLE
Missing _site and _plugins folder, can't generate sitemap

### ISSUE THREAD

**Issue by emTr0** [TolgaTatli/Moon#198]
While looking for a solution to #193 I thought I found one but it requires I have a _site and _plugins folder, which I don't  I added the plugins: - jekyll-sitemap to my _config.yml file but it doesn't do anything.

Reference: https://github.com/jekyll/jekyll-sitemap

Thanks.

**Comment by BagOfCoqs** [comment]
The `_site` folder is generated when you run jekyll build inside the theme's folder. Not sure about the `_plugins`
