### ISSUE TITLE
Mobile site

### ISSUE THREAD

**Issue by awnumar** [TolgaTatli/Moon#55]
Is there a way to disable the mobile site? In my opinion it is not as good looking as the full site and doesn't display featured images.

Also, on mobile there's an issue with rendering when scrolling. Is there a fix for that? It happens no matter what version of the site you use. I'm using chrome on Android.

**Comment by n2i** [comment]
I think it's not good idea when try to disable the mobile support feature. I mean, it seems like we're looking forward but trying to step backward.

Instead, we'll try to improve this one.

**Comment by libeclipse** [comment]
Oh the site looks beautiful when I choose to view the desktop one on my
phone. If it wasn't for the scrolling/rendering issue, it'd be perfect. I'm
not suggesting it's disabled for everyone, just instructions to disable it
myself and maybe set a custom default zoom level for phones.

**Comment by kamontat** [comment]
How to get sharing button in mobile ?

**Comment by libeclipse** [comment]
In addition to what I said before, rather than just disabling it manually, there could be an option in config.yml to disable it.
