### ISSUE TITLE
How to make new pages and put posts on those pages

### ISSUE THREAD

**Issue by astrojaket** [TolgaTatli/Moon#59]
Hi!

Thank you so much for making your awesome theme, I am having trouble getting posts to appear in different webpages on my site, I've been through the html code slowly but can't figure it out. Can you explain to me how to do this?

What I would like to do is have different web pages for different themed posts, ie new, vlog, etc.

All the best,

Jake Taylor

**Comment by TaylanTatli** [comment]
Sorry I was late. Still want me to explain this? Or did you solve already?

**Comment by astrojt** [comment]
I'm still not sure how to do it, can you help?

**Comment by DreamBao** [comment]
yeah, I have met the same problem

**Comment by jackieliutao** [comment]
I have the same problem.Search for help.
