### ISSUE TITLE
Link recent articles at the bottom of each article

### ISSUE THREAD

**Issue by awnumar** [TolgaTatli/Moon#64]
It'd be really cool if, say, the three or four most recent articles were linked to at the bottom of each post, kinda prompting the visitor to read them. Not sure how to make it look good and fit with the theme etc but you're the designer so you probably know that better than I do.

**Comment by TaylanTatli** [comment]
Recent articles or similar articles? What do you want? Tell me and I will do it. :smile:

**Comment by libeclipse** [comment]
You're enthusiastic lol.

Let's think about it. How would similar articles work? Would it be with the most similar keywords? What if a similar can't be found.

I think there should always be like a fixed amount of articles linked at the bottom. Maybe try and find very similar articles but if it fails then falls back onto the recent ones. If it only finds two similar articles then it should put the third as the most recent one. Also, we have to consider if there aren't that many posts. If there are only two articles on the entire site then you obv can't link to three.

**Comment by TaylanTatli** [comment]
There is a variable `site.related_posts` for jekyll here: https://jekyllrb.com/docs/variables/#site-variables

**Comment by libeclipse** [comment]
On github that'll be the most recent posts. Fair enough.
