### ISSUE TITLE
Mobile Issue

### ISSUE THREAD

**Issue by kamontat** [TolgaTatli/Moon#83]
In Mobile, 
How to get sharing button and goup button ??

**Comment by TaylanTatli** [comment]
I can add sharing buttons but goup button is really necessary for mobile?

**Comment by kamontat** [comment]
I don't know but I think might have some mobile that can't tap top bar to go to top
Sometime it might hard going to the top with content is so many

PS. I also have think about auto scroll down but the problem is it's don't have any thing that can detect scroll down
