### ISSUE TITLE
Draft Post

### ISSUE THREAD

**Issue by kamontat** [TolgaTatli/Moon#84]
is the theme have draft post???
Draft Post is post that may not finish it yet or still have something to check before publishing

**Comment by TaylanTatli** [comment]
Well it seems creating a `_drafts` folder is enough for it. https://jekyllrb.com/docs/drafts/
I don't understand what should I do.

**Comment by libeclipse** [comment]
I didn't realise that this was a thing. Could be pretty useful. How does it work?

**Comment by jtemporal** [comment]
@libeclipse just like @TaylanTatli said, create _drafts folder inside your project root...

I checked in Jekyll documentation... that can be found [here](https://jekyllrb.com/docs/drafts/)

**Comment by libeclipse** [comment]
Oh it requires a command line argument. Github won't support it then.

What I do is just do jekyll serve locally without drafting and just push
when ready. There's no point of drafting if it's done like described in the
docs, at least with github.

**Comment by jtemporal** [comment]
I don't understand what you mean by "Oh it requires a command line argument"... I meant to say that you'll have the _drafts folder on your project on github but it won't be used when generating the site... 

Suppose you want to write a post but you don't want to publish it, you could just leave it without a date but then when you give the `jekyll serve` command you'd get an error saying 'ERROR: YOUR SITE COULD NOT BE BUILT: Invalid date'... I believe that's what the _drafts is for... so you put the 'working in progress posts under a directory that won't be used during the build...

**Comment by libeclipse** [comment]
Oh so it's a whole feature to deal with a problem that isn't really a
problem.

On the docs it says that you have to give the --drafts option so it
wouldn't even work on github.
