### ISSUE TITLE
Add Google Tag Manager Snippet

### ISSUE THREAD

**Issue by jtemporal** [TolgaTatli/Moon#93]
Hi, I was wondering, based on the _includes directory, where would be the best place to put Google Tag Manager tracking snippet...
I put the first part under `_includes/header.html` and the second part under `_includes/nav.html` since this will insert right under the opening of the head tag and under the opening of the body tag respectively... But I'm not quite sure that is the best practice... Any thoughts on that matter?

**Comment by TaylanTatli** [comment]
Google suggest pasting `as close to the opening <head> tag and <body> tag`, so there is nothing wrong. You can also create seperate files in `_includes` folder and include it in head and body tags if you want more clean code.
